stages:
  - staging

before_script:
  - docker info

build-docker-image:
  stage: staging
  tags:
    - kbz
  only:
    - master 
  script:
    - ls -la
    - echo ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}:${CI_COMMIT_SHA} .
    - docker login -u ${CI_DEPLOY_USER} -p ${CI_DEPLOY_PASSWORD} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY}:${CI_COMMIT_SHA}
    - docker push ${CI_REGISTRY}:latest

deploy-2-staging:
  stage: staging
  tags:
    - kbz
  only:
    - master
  script:
    - docker rm profiling --force
    - docker run --name profiling --rm --detach --publish ${STAGING_PORT}:8000 -t ${CI_REGISTRY}:latest

