stages:
  - dev

before_script:
  - docker info

build-docker:
  stage: dev
  tags:
    - kbz
  only:
    - master 
  script:
    - ls -la
    - docker build -t $CI_REGISTRY:${CI_COMMIT_SHA} .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD ${CI_REGISTRY}:${CI_COMMIT_SHA}
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD ${CI_REGISTRY}:latest

